# Generated by Django 4.1.7 on 2023-08-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_pastevent', models.CharField(max_length=200)),
                ('summery_pastevent', models.TextField(blank=True, null=True)),
                ('content_pastevent', models.JSONField(blank=True, null=True)),
                ('image', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('videos', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
